# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'twparking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  #pod 'React', :path => '../node_modules/react-native'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Database'
  # Pods for twparking

  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  #pod 'RNLanguages', :path => '../node_modules/react-native-languages'

  target 'twparkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'twparking-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    #pod 'React', :path => '../node_modules/react-native'
    pod 'Firebase/Core'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Database'
  # Pods for twparking-tvOS

  target 'twparking-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
